<?php

namespace Container25LyEpk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dul0n3kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dul0n3k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dul0n3k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProjetController::CreateOp' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\ProjetController::delete' => ['privates', '.service_locator.vL5fXOO', 'get_ServiceLocator_VL5fXOOService', true],
            'App\\Controller\\ProjetController::listOperation' => ['privates', '.service_locator.OW0sPmp', 'get_ServiceLocator_OW0sPmpService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.HchEEiQ', 'get_ServiceLocator_HchEEiQService', true],
            'App\\Controller\\SecurityController::show' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ProjetController:CreateOp' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\ProjetController:delete' => ['privates', '.service_locator.vL5fXOO', 'get_ServiceLocator_VL5fXOOService', true],
            'App\\Controller\\ProjetController:listOperation' => ['privates', '.service_locator.OW0sPmp', 'get_ServiceLocator_OW0sPmpService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.HchEEiQ', 'get_ServiceLocator_HchEEiQService', true],
            'App\\Controller\\SecurityController:show' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ProjetController::CreateOp' => '?',
            'App\\Controller\\ProjetController::delete' => '?',
            'App\\Controller\\ProjetController::listOperation' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\SecurityController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProjetController:CreateOp' => '?',
            'App\\Controller\\ProjetController:delete' => '?',
            'App\\Controller\\ProjetController:listOperation' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\SecurityController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
