<?php

namespace Container1F4C5sP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7urqAXV.App\Entity\Operation' shared service.
     *
     * @return \App\Entity\Operation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7urqAXV": it references class "App\\Entity\\Operation" but no such service exists.');
    }
}
