<?php

namespace ContainerXFROqRg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QpBdbVfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QpBdbVf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QpBdbVf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\ChiffreAffaireRepository', 'getChiffreAffaireRepositoryService', true],
            'repoOp' => ['privates', 'App\\Repository\\OperationRepository', 'getOperationRepositoryService', true],
            'repoUser' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ChiffreAffaireRepository',
            'repoOp' => 'App\\Repository\\OperationRepository',
            'repoUser' => 'App\\Repository\\UserRepository',
        ]);
    }
}
