<?php

namespace ContainerXFROqRg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YPFExj4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YPFExj4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YPFExj4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProjetController::AfficherCA' => ['privates', '.service_locator.nB1rC.C', 'get_ServiceLocator_NB1rC_CService', true],
            'App\\Controller\\ProjetController::CreateOp' => ['privates', '.service_locator.m5HakWt', 'get_ServiceLocator_M5HakWtService', true],
            'App\\Controller\\ProjetController::delete' => ['privates', '.service_locator.vL5fXOO', 'get_ServiceLocator_VL5fXOOService', true],
            'App\\Controller\\ProjetController::home' => ['privates', '.service_locator.OW0sPmp', 'get_ServiceLocator_OW0sPmpService', true],
            'App\\Controller\\ProjetController::index' => ['privates', '.service_locator.QpBdbVf', 'get_ServiceLocator_QpBdbVfService', true],
            'App\\Controller\\ProjetController::listOperation' => ['privates', '.service_locator.OW0sPmp', 'get_ServiceLocator_OW0sPmpService', true],
            'App\\Controller\\ProjetController::terminer' => ['privates', '.service_locator.gn8QSXQ', 'get_ServiceLocator_Gn8QSXQService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.HchEEiQ', 'get_ServiceLocator_HchEEiQService', true],
            'App\\Controller\\SecurityController::show' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ProjetController:AfficherCA' => ['privates', '.service_locator.nB1rC.C', 'get_ServiceLocator_NB1rC_CService', true],
            'App\\Controller\\ProjetController:CreateOp' => ['privates', '.service_locator.m5HakWt', 'get_ServiceLocator_M5HakWtService', true],
            'App\\Controller\\ProjetController:delete' => ['privates', '.service_locator.vL5fXOO', 'get_ServiceLocator_VL5fXOOService', true],
            'App\\Controller\\ProjetController:home' => ['privates', '.service_locator.OW0sPmp', 'get_ServiceLocator_OW0sPmpService', true],
            'App\\Controller\\ProjetController:index' => ['privates', '.service_locator.QpBdbVf', 'get_ServiceLocator_QpBdbVfService', true],
            'App\\Controller\\ProjetController:listOperation' => ['privates', '.service_locator.OW0sPmp', 'get_ServiceLocator_OW0sPmpService', true],
            'App\\Controller\\ProjetController:terminer' => ['privates', '.service_locator.gn8QSXQ', 'get_ServiceLocator_Gn8QSXQService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.HchEEiQ', 'get_ServiceLocator_HchEEiQService', true],
            'App\\Controller\\SecurityController:show' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ProjetController::AfficherCA' => '?',
            'App\\Controller\\ProjetController::CreateOp' => '?',
            'App\\Controller\\ProjetController::delete' => '?',
            'App\\Controller\\ProjetController::home' => '?',
            'App\\Controller\\ProjetController::index' => '?',
            'App\\Controller\\ProjetController::listOperation' => '?',
            'App\\Controller\\ProjetController::terminer' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\SecurityController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProjetController:AfficherCA' => '?',
            'App\\Controller\\ProjetController:CreateOp' => '?',
            'App\\Controller\\ProjetController:delete' => '?',
            'App\\Controller\\ProjetController:home' => '?',
            'App\\Controller\\ProjetController:index' => '?',
            'App\\Controller\\ProjetController:listOperation' => '?',
            'App\\Controller\\ProjetController:terminer' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\SecurityController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
