<?php

namespace ContainerInAWb4j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7urqAXVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7urqAXV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7urqAXV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'op' => ['privates', '.errored..service_locator.7urqAXV.App\\Entity\\Operation', NULL, 'Cannot autowire service ".service_locator.7urqAXV": it references class "App\\Entity\\Operation" but no such service exists.'],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'manager' => '?',
            'op' => 'App\\Entity\\Operation',
            'repo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
