<?php

namespace ContainerAch9eRQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NB1rC_CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nB1rC.C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nB1rC.C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\ChiffreAffaireRepository', 'getChiffreAffaireRepositoryService', true],
        ], [
            'manager' => '?',
            'repo' => 'App\\Repository\\ChiffreAffaireRepository',
        ]);
    }
}
