<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHfouVr0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHfouVr0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHfouVr0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHfouVr0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHfouVr0\App_KernelDevDebugContainer([
    'container.build_hash' => 'HfouVr0',
    'container.build_id' => '8b67e255',
    'container.build_time' => 1649677394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHfouVr0');
