<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQALo3Fn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQALo3Fn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQALo3Fn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQALo3Fn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQALo3Fn\App_KernelDevDebugContainer([
    'container.build_hash' => 'QALo3Fn',
    'container.build_id' => '69b4fdc8',
    'container.build_time' => 1649857215,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQALo3Fn');
