<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAch9eRQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAch9eRQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAch9eRQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAch9eRQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAch9eRQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ach9eRQ',
    'container.build_id' => 'b8144568',
    'container.build_time' => 1649931787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAch9eRQ');
